config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get 'signup', to: 'registrations#new'
  post 'signup', to: 'registrations#create'

  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    resources :user_details
  end
  put 'funds/deposit', to: 'users#deposit', as: 'funds_deposit'
  put 'funds/send', to: 'users#send_money', as: 'funds_send'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_detail, dependent: :destroy
  accepts_nested_attributes_for :user_detail
  has_secure_password

  VALID_EMAIL_REGEX = /\A[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+\z/

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX, message: 'must be a valid email address!' },
                    uniqueness: true
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  belongs_to :user

  validates :name, presence: true

  def transfer(receiver_email, amount)
    sender_balance = balance.to_r

    if receiver = User.find_by(email: receiver_email)
      receiver_details = UserDetail.find_by(user_id: receiver.id)
      if sender_balance >= amount
        update(balance: (sender_balance - amount).to_f)
        receiver_details.update(balance: (receiver_details.balance + amount).to_f)
      else
        errors.add(:balance, 'is insufficient for this transaction!')
      end
    else
      errors.add(:receiver, "no user found with email: #{receiver_email}")
    end
  end

  def deposit(amount)
    balance = self.balance.to_r
    update(balance: (balance + amount).to_f)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
    @user.build_user_detail
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Successfully created account!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.required(:user).permit(:name, :email, :password, :password_confirmation, user_detail_attributes: [:name])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully'
    else
      flash[:alert] = 'Invalid email or password'
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to signin_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[index update deposit send_money]

  def index
    set_user
    check_session
  end

  def edit
    set_user
    check_session
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'Profile updated successfully!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    set_user
    @user.destroy
    session[:user_id] = nil
    redirect_to signin_path
  end

  def deposit
    user = User.find_by(id: session[:user_id])
    amount = params[:amount].to_r

    ActiveRecord::Base.transaction do
      user.user_detail.deposit(amount)
    end
    redirect_to root_path
  end

  def send_money
    amount = params[:amount].to_r

    ActiveRecord::Base.transaction do
      @user.user_detail.transfer(params[:receiver], amount)
      raise ActiveRecord::Rollback unless @user.user_detail.errors.empty?
    end

    if @user.user_detail.errors.empty?
      redirect_to root_path
    else
      @users = User.all
      render :index, status: :unprocessable_entity
    end
  end

  private

  def set_user
    return unless session[:user_id]

    @user = User.find_by(id: session[:user_id])
  end

  def check_session
    if @user
      @users = User.all
    else
      redirect_to signin_path
    end
  end

  def user_params
    params.required(:user).permit(:name, :email, :password, :password_confirmation,
                                  user_detail_attributes: %i[id name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LivixChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="text-center" style="max-width: 25rem; width: 100%;">
        <h1 class="mb-5">Edit profile</h1>

        <%= form_with model: @user do |form| %>
            <% if @user.errors.any? %>
                <div class="alert alert-danger">
                    <% @user.errors.full_messages.each do |message| %>
                        <div><%= message %></div>
                    <% end %>
                </div>
            <% end %>

            <%= form.fields_for :user_detail do |user_detail| %>
                <div class="pt-5 mb-3">
                    <%= user_detail.label :name, class: "form-label" %>
                    <%= user_detail.text_field :name, class: "form-control text-center", placeholder: "Matthews" %>
                </div>
            <% end %>

            <div class="mb-3">
                <%= form.label :email, class: "form-label" %>
                <%= form.email_field :email, class: "form-control text-center", placeholder: "matthews@example.com" %>
            </div>

            <div class="mb-3">
                <%= form.label :password, class: "form-label" %>
                <%= form.password_field :password, class: "form-control text-center", placeholder: "password" %>
            </div>

            <div class="mb-3">
                <%= form.label :password_confirmation, class: "form-label" %>
                <%= form.password_field :password_confirmation, class: "form-control text-center", placeholder: "password" %>
            </div>

            <div class="d-grid gap-2 pt-5">
                <%= form.submit "Save", class: "btn btn-primary mt-4" %>
                <%= link_to "Delete", user_path(@user), class: "btn btn-danger mt-2", data: {
                                    turbo_method: :delete,
                                    turbo_confirm: "Do you really want to delete your account?"
                                } %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<div class="text-center">
    <% if @user.user_detail.errors.any? %>
        <% @user.user_detail.errors.full_messages.each do |message| %>
            <div class="alert alert-warning"><%= message %></div>
        <% end %>
    <% end %>
    <div class="container d-flex justify-content-between align-items-center mt-5">
        <h1 class="flex-grow-1">Hello <%= @user.user_detail.name %>!</h1>
        <%= link_to "Edit", edit_user_path(@user), class: "btn btn-lg btn-primary", style: "margin-right: 1rem;" %>
        <%= button_to "Logout", logout_path, class: "btn btn-lg btn-danger", method: :delete %>
    </div>
</div>
<div class="container d-flex justify-content-center">
    <div class="column m-5 text-center border" style="max-width: 50rem; width: 100%;">
        <h1 class="m-3">Users to transfer money!</h1>
        <% @users.each do |user| %>
            <% unless @user == user %>
                <div class="m-3">
                    <%= user.user_detail.name %> - <%= user.email %>, <%= number_to_currency(user.user_detail.balance, unit: "US$", precision: 2) %>
                </div>
            <% end %>
        <% end %>
    </div>
    <div class="column m-5 text-center border" style="max-width: 50rem; width: 100%;">
        <div class="m-3">
            <h1>Balance: <%= number_to_currency(@user.user_detail.balance, unit: "US$", precision: 2) %></h1>
        </div>
        <%= form_with url: funds_deposit_path(@user.id), method: :put do |deposit_form| %>
            <div class="m-3">
                <%= deposit_form.label "amount to deposit", class: "form-label" %>
                <%= deposit_form.text_field "amount", class: "form-control text-center", placeholder: "$200.00" %>
            </div>
            <div class="m-3 d-grid gap-2">
                <%= deposit_form.submit "Deposit", class: "btn btn-success" %>
            </div>
        <% end %>

        <%= form_with url: funds_send_path, method: :put do |send_form| %>
            <div class="row m-3">
                <div class="col md-6">
                    <%= send_form.label "User to send money", class: "form-label" %>
                    <%= send_form.text_field "receiver", class: "form-control text-center", placeholder: "matthews@example.com" %>
                </div>
                <div class="col md-6">
                    <%= send_form.label "Amount to send", class: "form-label" %>
                    <%= send_form.text_field "amount", class: "form-control text-center", placeholder: "$200.00" %>
                </div>
            </div>
            <div class="m-3 d-grid gap-2">
                <%= send_form.submit "Send", class: "btn btn-success" %>
            </div>
        <% end %>
    </div>
</div>